version: 2.1

filters: &filters
  tags:
    only: /.*/

orbs:
  orb-tools: circleci/orb-tools@11.5
  orb: hubci/notify@dev:<< pipeline.git.revision >>

workflows:
  int-testing-wf:
    jobs:
      - int-test-notify-mattermost:
          filters: *filters
      - int-test-failed-mattermost:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: hubci/notify
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - int-test-notify-mattermost
            - int-test-failed-mattermost
          context: circleci-ctx
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  int-test-notify-mattermost:
    docker:
      - image: cimg/base:2023.01
    steps:
      - orb/notify-mattermost:
          text: "This message is from testing the Mattermost CircleCI orb. It can be found here: ${CIRCLE_BUILD_URL}."
  int-test-failed-mattermost:
    docker:
      - image: cimg/base:2023.01
    steps:
      # This has to be manually tested. Change to 'exit 1' to test.
      - run: echo "Simulate a step failure." && exit 0
      - orb/failed-mattermost
